<?php

/*
 * $Id: index.php 5937 2010-11-21 17:42:55Z crob $
 *
 * Copyright 2001, 2011 Thomas Belliard, Laurent Delineau, Edouard Hue, Eric Lebrun
 *
 * This file is part of GEPI.
 *
 * GEPI is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * GEPI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GEPI; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// Initialisations files
require_once("../lib/initialisations.inc.php");
// Resume session
$resultat_session = $session_gepi->security_check();
if ($resultat_session == 'c') {
header("Location: ../utilisateurs/mon_compte.php?change_mdp=yes");
die();

} else if ($resultat_session == '0') {
    header("Location: ../logout.php?auto=1");
die();
};

if (!checkAccess()) {
    header("Location: ../logout.php?auto=1");
die();
}

// Page bourrinée... la gestion du token n'est pas faite... et ne sera faite que si quelqu'un utilise encore ce mode d'initialisation et le manifeste sur la liste de diffusion gepi-users
check_token();

if (!function_exists("dbase_open"))  {
    $msg = "CAUTION : PHP is not configured to manage files GEP (dbf). The extension d_base is not active. Contact the administrator of the server to correct the problem.";
}

//**************** EN-TETE *****************
$titre_page = "Tool of initialization of the year";
require_once("../lib/header.inc");
//**************** FIN EN-TETE *****************
?>
<p class=bold><a href="../gestion/index.php"><img src='../images/icons/back.png' alt='Return' class='back_link'/> Return</a></p>

<p>You will carry out the initialization of the school year which has just begun.</p>
<ul>
<li>
	<p>During the procedure, if necessary, certain data of the last year will be definitively erased from GEPI base (students, notes, appreciations, ...).<br />
	Only will be preserved the following data :<br /></p>
	<ul>
		<li><p>data relating to the schools,</p></li>
		<li><p>data relating to the classes : short headings, long headings, number of periods and names of the periods,</p></li>
		<li><p>data relating to the courses : complete identifiers and headings,</p></li>
		<li><p>data relating to the users (professors, administrators, ...). Concerning the professors, the courses taught by the professors are preserved,</p></li>
		<li><p>Data relating to the various types of AID.</p></li>
	</ul>
</li>
<li>
	<?php
	//==================================
	// RNE de l'établissement pour comparer avec le RNE de l'établissement de l'année précédente
	$gepiSchoolRne=getSettingValue("gepiSchoolRne") ? getSettingValue("gepiSchoolRne") : "";
	//==================================
	if($gepiSchoolRne=="") {
		echo "<p><b style='color:red;'>Attention</b>: Le RNE de l'établissement n'est pas renseigné dans 'Gestion générale/<a href='../gestion/param_gen.php' target='_blank'>Configuration générale</a>'<br />Cela peut perturber l'import de l'établissement d'origine des élèves.<br />Vous devriez corriger avant de poursuivre.</p>\n";
	}
	?>

	<p>Initialization is carried out in four phases, each one requiring a particular file GEP <b>or CSV</b>:</p>
	<ul>
		<li><p>You must have files F_ELE.DBF and F_ERE.DBF generated by AutoSco.<br />
		To generate the F_ELE.CSV corresponding to the F_ELE.DBF since Sconet is rather easy except for the ERENO which is not recovered and then generate a F_ERE.CSV is not convenient.<br />
		It is indeed necessary to arbitrarily fix a ERENO to make the
link between parents and children and to retrieve only the desired entries of Sconet for the parents (<i>one recovers there more than two lines by student...</i>)...<br />In short, I left in plan.</p></li>
		<li><p>You can generate files F_TMT.CSV, F_MEN.CSV and F_GPD.CSV using export XML of STS once timetable is done.</p>
		<p>You can also supplement partially the F_WIND.CSV of this way.<br />
		Partially because certain fields are not recovered:</p>
		<ul>
			<!--li>le NUMEN (INDNNI) utilisé comme mot de passe par défaut par GEPI n'est pas récupéré.<br />
			Vous devrez compléter les champs mots-de-passe (<i>ou accepter les mots de passe aléatoires proposés (les noter/imprimer pour transmettre aux collègues)</i>).</li-->
			<li>NUMEN (INDNNI) used as by default password by GEPI is not recovered.<br />
			It is then proposed to define a random password or to use the date of birth in the place.</li>
			<li>Civility is not recovered either (<i>but it is rather easy to compete it</i>).</li>
			<li>Lastly, field FONCCO is not filled either (<i>but it is in theory 'ENS' for all the teachers</i>).</li>
		</ul>
		<p><a href='lecture_xml_sts_emp.php'>Generate files CSV starting from export XML of STS</a>.</p></li>
	</ul>
</li>
<li>
	<p>To proceed to the imports:</p>
	<ul>
		<li><p><a href='step1.php'>Proceed to the first phase</a> of importation of the students,  of constitution of the classes and of assignment of the students in the classes : the file < b>F_ELE.DBF</b > is necessary.</p></li>
		<li><p><a href='responsables.php'>Proceed to the second phase</a> of importation of the responsibles of the students: the file <b>F_ERE.DBF</b> is necessary.</p></li>
		<li><p><a href='disciplines_csv.php'>Proceed to the third phase</a> of importation of the courses: the file <b>F_tmt.csv</b> is necessary.</p></li>
		<li><p><a href='prof_csv.php'> Proceed to the fourth phase</a> of importation of the professors: the file <b>F_wind.csv</b> is necessary.</p></li>
		<li><p><a href='prof_disc_classe_csv.php'>Proceed to the fifth phase</a> of assignment of the courses to each professor, of assignment of the professors in each class and of definition of the options followed by the students : files <b>F_men.csv</b> and <b>F_gpd.csv</b> are necessary.</p></li>

		<li><p><a href='init_pp.php'>Proceed to the sixth phase</a>: Initialization of the principal professors.</p></li>

		<li><p><a href='clean_tables.php'>Proceed to the seventh phase</a> of cleaning of the data: useless data imported from files GEP during of the various phases of initialization will be erased!</p></li>

	</ul>
</li>
<li>
	<p>Once all procedure of initialization of the data finished, it will be possible for you to make all the modifications necessary individually by the means of the management tools included in <b>GEPI</b>.</p>
</li>
</ul>
<?php require("../lib/footer.inc.php");?>